CC=cl.exe
CFLAGS_TEST=/TC /Od /Zi /W4
SRC_DIR=src
OBJ_DIR=..\..\obj
FIXTURE_DIR=extras\fixture\src

# not ideal but it works for now
DEBUG_OBJS=$(OBJ_DIR)\unity.dobj $(OBJ_DIR)\unity_fixture.dobj

all: $(DEBUG_OBJS)

{$(SRC_DIR)\}.c{$(OBJ_DIR)\}.dobj:
	$(CC) $(CFLAGS_TEST) /c /Fo$@ $**
{$(FIXTURE_DIR)\}.c{$(OBJ_DIR)\}.dobj:
	$(CC) $(CFLAGS_TEST) /c /Fo$@ $** /I $(SRC_DIR)